Ratibor
777lexus777/new-site pull request #2
Opened 2023-11-13 03:54 UTC by 777lexus777

добавил цсс 13.11

2023-11-13 07:25 UTC, Opanch88 requested changes
ibdex заьираю

2023-11-18 07:40 UTC, Opanch88 approved these changes
approve , сливаю

2023-11-18 09:42 UTC, closed without merging

2023-11-18 09:43 UTC, 777lexus777 commented
klho

2023-11-20 19:21 UTC, 777lexus777 reviewed
123